setup:
  env:
    name: BipedalWalker-v3
    config: src/rl_trainer/configs/environments/bipedal_walker.yaml
  algo:
    name: ppo_baseline
    config: src/rl_trainer/configs/algorithms/ppo.yaml
  seed: 42

mlflow:
  tracking_uri:  http://127.0.0.1:8080
  experiment:  ${setup.env.name}-${setup.algo.name}-exp${now:%Y%m%d%H%M}
  run_name:    ${now:%Y%m%d%H%M%S}
  tags:
    env_name: ${setup.env.name}
    algo: ${setup.algo.name}
    time: run:${now:%H%M%S}
